### ISSUE TITLE
notifyDataSetChanged() Does not work

### ISSUE THREAD

**Issue by IRMobydick** [grennis/ExpandableRecyclerView#2]
Hi there
There is a issue with this adapter, I've to get categories and their subcategories from rest API.
As usual after parsing and making my List and assign that to Adapter, I use `notifyDatasetChanged()` method to notify Adapter.
Issue is there! Adapter does not recognize the change!

another odd action: `notifyDatasetChanged()` close the open parent but the arrow still remain in it's open state! ( When I populated the adapter with fake data like yours sample app ).

Is there any custom method for this?

**Comment by grennis** [comment]
Correct, `notifyDataSetChanged` will rebuild the list using the underlying data set. However, in the expandable recycler view, the underlying data set is the flattened list of items. You would need to rebuild this list by calling `setItems` which will then call notifyDataSetChanged for you. Note that incrementally adding or removing items is not supported because I didn't need it. Contributions welcome!

**Comment by IRMobydick** [comment]
Hi there, Thanks for your prompt response.
Another question is, How can get position of selected child?
`visibleItems.get(position).ROW_TITLE`

I want to show selected state to user, then I have a `SparseBooleanArray` to map selected position to Boolean to change child background to selected.

But! when user select one child from a parent, open another parent! a child from late parent may be selected!!! o_O

How you resolved this issue?

**Comment by grennis** [comment]
You can get the index in the array of all items given the index of the item position:

```
int allItemsPosition = indexList.get(visiblePosition);
```
